### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by SebastienDaniel** [DemocraciaEnRed/website#36]
On the english version of the website, the links to the balance sheets lead to 404 errors.
![image](https://cloud.githubusercontent.com/assets/445482/13987260/1db69b26-f0dd-11e5-94bf-23157482a1fa.png)

The problem is caused by `en/` being prepended to the resource paths, for example:
**spanish**
`http://democraciaenred.org/images/balances/2014-2015.pdf`

**english**
`http://democraciaenred.org/en/images/balances/2014-2015.pdf`

Also, the link to `democracyos.org` is broken on the spanish version of the site
![image](https://cloud.githubusercontent.com/assets/445482/13987583/a397e122-f0de-11e5-8135-c4e49c33f986.png)

Because it is pointing to a `https` url, where-as the domain is running on `http`

**Comment by SebastienDaniel** [comment]
I can make the fixes if you like.
I only need to know if the balance sheets (english) should redirect to the spanish balance sheets, or if we should only remove the links entirely.

**Comment by mjlescano** [comment]
It should redirect to the spanish versions of the sheets, thanks!

**Comment by florlafuente** [comment]
Solved.
