### ISSUE TITLE
Links a proyectos existentes

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/website#9]
A dónde navego cuando hago click en el thumbnail de un proyecto? Lleva a otra página?

**Comment by ghost** [comment]
Acá algunas ideas. https://vimeo.com/128897877 Pass: fundacion
Además quiero hacer lo de las sillas voladoras.

**Comment by gvilarino** [comment]
@sebafer estéticamente son muy bonitas todas. Ahora, en cuanto a cosas que no me copan tanto:
- En gral, no veo nada de eso funcionando en mobile. Para mí que nuestro website sea responsive es un deal-breaker.
- El site 1 (de las cocinas) es un ejemplo de un site "vidriera". El parallax es muy eye candy pero es algo que se está abandonando por cuestiones tanto de performance como de que hacen que todo sea muy pesado, aparte de que en mobile suele andar para atrás y no se aprecia a menos que la pantalla sea del dispositivo sea muy grande y/o tenga alta definición.
- El site 2 casi lo mismo que el primero. Es un portfolio de diseño donde lo estético prima por sobre lo accesible. Aún así, la parte inferior me gusta mucho.
- El site 3 es el que más me resulta. Limpio y simple, enfocado en comunicar 1 sola cosa. Para mí el parallax ahí está de más.

¿Tenés las versiones mobile de esos sitios?

**Comment by ghost** [comment]
@gvilarino me parece genial que que sea responsive sea un deal-breaker, me queda clarísimo que la navegación cada vez mas será a través de dispositivos móviles.

En el video se ven las urls, igual te las pego acá, los tres funcionan "como pueden" en mobile, se nota que quizás tienen alguna cosita hecha especialmente para mobile (La que resulta mejor es la segunda, tiene cosas interesantes)

1- http://www.bulthauppresentatie.nl/
2- http://www.squarespace.com/
3- http://www.officeline.se/kampanj/

De todas formas los ejemplos apuntaban a ver como sin dejar de ser una single page web podemos meter cosas del tipo galería por ejemplo para mostrar los proyectos.

**Comment by gvilarino** [comment]
> De todas formas los ejemplos apuntaban a ver como sin dejar de ser una single page web podemos meter cosas del tipo galería por ejemplo para mostrar los proyectos.

Para eso la que más me gusta creo que es lo que hace la primera opción al principio.
